"""
Port schemas package
"""
# Import all schemas for easy access
from app.schemas.port.vessel import (
    VesselBase,
    VesselCreate,
    VesselUpdate,
    VesselResponse,
    VesselDetailResponse,
    VesselListResponse,
    VesselSearchParams,
)

from app.schemas.port.berth import (
    BerthBase,
    BerthCreate,
    BerthUpdate,
    BerthResponse,
    BerthDetailResponse,
    BerthOccupancyResponse,
    BerthCapacityResponse,
    BerthListResponse,
    BerthSearchParams,
)

from app.schemas.port.loading_operation import (
    CargoBase,
    CargoCreate,
    CargoUpdate,
    CargoResponse,
    OperationEventBase,
    OperationEventCreate,
    OperationEventResponse,
    LoadingOperationBase,
    LoadingOperationCreate,
    LoadingOperationUpdate,
    LoadingOperationResponse,
    LoadingOperationDetailResponse,
    LoadingOperationProgressResponse,
    LoadingOperationListResponse,
    LoadingOperationSearchParams,
    OperationStartRequest,
    OperationPauseRequest,
    OperationResumeRequest,
    OperationCompleteRequest,
    OperationDelayRequest,
)

from app.schemas.port.analytics import (
    PortKPIResponse,
    PerformanceMetricsResponse,
    EquipmentPerformanceResponse,
    TrendDataPoint,
    TrendResponse,
    MultipleTrendsResponse,
    CommodityBreakdownResponse,
    CommodityAnalyticsResponse,
    DailyReportResponse,
    OperationReportResponse,
    CustomReportRequest,
    CustomReportResponse,
    AnalyticsQueryParams,
    TrendQueryParams,
)

__all__ = [
    # Vessel schemas
    "VesselBase",
    "VesselCreate",
    "VesselUpdate",
    "VesselResponse",
    "VesselDetailResponse",
    "VesselListResponse",
    "VesselSearchParams",
    # Berth schemas
    "BerthBase",
    "BerthCreate",
    "BerthUpdate",
    "BerthResponse",
    "BerthDetailResponse",
    "BerthOccupancyResponse",
    "BerthCapacityResponse",
    "BerthListResponse",
    "BerthSearchParams",
    # Loading operation schemas
    "CargoBase",
    "CargoCreate",
    "CargoUpdate",
    "CargoResponse",
    "OperationEventBase",
    "OperationEventCreate",
    "OperationEventResponse",
    "LoadingOperationBase",
    "LoadingOperationCreate",
    "LoadingOperationUpdate",
    "LoadingOperationResponse",
    "LoadingOperationDetailResponse",
    "LoadingOperationProgressResponse",
    "LoadingOperationListResponse",
    "LoadingOperationSearchParams",
    "OperationStartRequest",
    "OperationPauseRequest",
    "OperationResumeRequest",
    "OperationCompleteRequest",
    "OperationDelayRequest",
    # Analytics schemas
    "PortKPIResponse",
    "PerformanceMetricsResponse",
    "EquipmentPerformanceResponse",
    "TrendDataPoint",
    "TrendResponse",
    "MultipleTrendsResponse",
    "CommodityBreakdownResponse",
    "CommodityAnalyticsResponse",
    "DailyReportResponse",
    "OperationReportResponse",
    "CustomReportRequest",
    "CustomReportResponse",
    "AnalyticsQueryParams",
    "TrendQueryParams",
]
