/**
 * AI Insights API Client
 * Provides access to insights generated by the Autonomous Agent
 */

import { apiClient } from './client';

export interface Insight {
  id: string;
  title: string;
  description: string;
  category: 'anomaly' | 'optimization' | 'alert' | 'trend' | 'prediction';
  severity: 'critical' | 'high' | 'medium' | 'low' | 'info';
  tags: string[];
  metrics: Record<string, any>;
  recommendations: string[];
  timestamp: string;
  data: Record<string, any>;
}

export interface InsightsSummary {
  total_insights: number;
  by_category: Record<string, number>;
  by_severity: Record<string, number>;
  latest_timestamp: string | null;
}

export interface InsightsResponse {
  total: number;
  insights: Insight[];
  filters: {
    category: string | null;
    severity: string | null;
  };
}

/**
 * Get all autonomous insights with optional filters
 */
export const getInsights = async (params?: {
  category?: string;
  severity?: string;
  limit?: number;
}): Promise<InsightsResponse> => {
  const queryParams = new URLSearchParams();

  if (params?.category) queryParams.append('category', params.category);
  if (params?.severity) queryParams.append('severity', params.severity);
  if (params?.limit) queryParams.append('limit', params.limit.toString());

  const response = await apiClient.get(
    `/api/v1/ai/insights/autonomous${queryParams.toString() ? '?' + queryParams.toString() : ''}`
  );

  return response.data;
};

/**
 * Get insights summary with statistics
 */
export const getInsightsSummary = async (): Promise<InsightsSummary> => {
  const response = await apiClient.get('/api/v1/ai/insights/autonomous/summary');
  return response.data;
};

/**
 * Get recent insights (shortcut for latest N insights)
 */
export const getRecentInsights = async (limit: number = 10): Promise<Insight[]> => {
  const response = await apiClient.get(`/api/v1/ai/insights/autonomous?limit=${limit}`);
  return response.data.insights;
};

/**
 * Get insights filtered by category
 */
export const getInsightsByCategory = async (
  category: string,
  limit: number = 50
): Promise<Insight[]> => {
  const response = await apiClient.get(
    `/api/v1/ai/insights/autonomous?category=${category}&limit=${limit}`
  );
  return response.data.insights;
};

/**
 * Get insights filtered by severity
 */
export const getInsightsBySeverity = async (
  severity: string,
  limit: number = 50
): Promise<Insight[]> => {
  const response = await apiClient.get(
    `/api/v1/ai/insights/autonomous?severity=${severity}&limit=${limit}`
  );
  return response.data.insights;
};

/**
 * Manually trigger a monitoring cycle
 */
export const triggerMonitoringCycle = async (): Promise<{
  status: string;
  message: string;
  insights_generated: number;
}> => {
  const response = await apiClient.post('/api/v1/ai/insights/autonomous/trigger');
  return response.data;
};

/**
 * Get insights for a specific tag
 */
export const getTagInsights = async (tagId: string): Promise<any> => {
  const response = await apiClient.get(`/api/v1/ai/insights/realtime/${tagId}`);
  return response.data;
};

/**
 * Helper functions
 */

export const getSeverityColor = (severity: Insight['severity']): string => {
  const colors = {
    critical: 'text-red-600 bg-red-50 border-red-200',
    high: 'text-orange-600 bg-orange-50 border-orange-200',
    medium: 'text-yellow-600 bg-yellow-50 border-yellow-200',
    low: 'text-blue-600 bg-blue-50 border-blue-200',
    info: 'text-gray-600 bg-gray-50 border-gray-200',
  };
  return colors[severity] || colors.info;
};

export const getCategoryIcon = (category: Insight['category']): string => {
  const icons = {
    anomaly: '🔍',
    optimization: '⚡',
    alert: '⚠️',
    trend: '📈',
    prediction: '🔮',
  };
  return icons[category] || '💡';
};

export const getCategoryLabel = (category: Insight['category']): string => {
  const labels = {
    anomaly: 'Anomalia',
    optimization: 'Otimização',
    alert: 'Alerta',
    trend: 'Tendência',
    prediction: 'Previsão',
  };
  return labels[category] || category;
};

export const getSeverityLabel = (severity: Insight['severity']): string => {
  const labels = {
    critical: 'Crítico',
    high: 'Alto',
    medium: 'Médio',
    low: 'Baixo',
    info: 'Informativo',
  };
  return labels[severity] || severity;
};

export const formatTimestamp = (timestamp: string): string => {
  try {
    const date = new Date(timestamp);
    const now = new Date();
    const diffMs = now.getTime() - date.getTime();
    const diffMins = Math.floor(diffMs / 60000);
    const diffHours = Math.floor(diffMs / 3600000);
    const diffDays = Math.floor(diffMs / 86400000);

    if (diffMins < 1) return 'Agora mesmo';
    if (diffMins < 60) return `${diffMins}min atrás`;
    if (diffHours < 24) return `${diffHours}h atrás`;
    if (diffDays < 7) return `${diffDays}d atrás`;

    return date.toLocaleDateString('pt-BR', {
      day: '2-digit',
      month: 'short',
      hour: '2-digit',
      minute: '2-digit'
    });
  } catch {
    return timestamp;
  }
};
