"""
Autonomous AI Agent Service - Continuous Process Monitoring

This service runs continuously to:
- Monitor process in real-time
- Detect anomalies and patterns
- Generate proactive insights
- Suggest improvements and optimizations
- Alert on critical conditions
"""

import asyncio
import logging
from datetime import datetime, timedelta
from typing import List, Dict, Any, Optional
from sqlalchemy.ext.asyncio import AsyncSession
from sqlalchemy import select
import json

from app.models.tag import Tag
from app.services.data_service import DataService
from app.services.agent_tools import AgentToolkit
from app.services.influxdb import influxdb_service

logger = logging.getLogger(__name__)


class AutonomousInsight:
    """Represents an autonomous insight generated by the agent"""
    
    def __init__(
        self,
        insight_id: str,
        title: str,
        description: str,
        category: str,  # anomaly, optimization, alert, trend, prediction
        severity: str,  # critical, high, medium, low, info
        tags: List[str],
        metrics: Dict[str, Any],
        recommendations: List[str],
        timestamp: datetime,
        data: Optional[Dict[str, Any]] = None
    ):
        self.insight_id = insight_id
        self.title = title
        self.description = description
        self.category = category
        self.severity = severity
        self.tags = tags
        self.metrics = metrics
        self.recommendations = recommendations
        self.timestamp = timestamp
        self.data = data or {}
    
    def to_dict(self) -> Dict[str, Any]:
        return {
            "id": self.insight_id,
            "title": self.title,
            "description": self.description,
            "category": self.category,
            "severity": self.severity,
            "tags": self.tags,
            "metrics": self.metrics,
            "recommendations": self.recommendations,
            "timestamp": self.timestamp.isoformat(),
            "data": self.data
        }


class AutonomousAgent:
    """
    Autonomous AI Agent for continuous process monitoring
    
    This agent runs in the background, constantly monitoring the process
    and generating insights without user intervention.
    """
    
    def __init__(self):
        self.insights: List[AutonomousInsight] = []
        self.max_insights = 100  # Keep last 100 insights
        self.monitoring_interval = 60  # Monitor every 60 seconds
        self.is_running = False
        
    async def start(self):
        """Start autonomous monitoring"""
        from app.db.session import AsyncSessionLocal
        
        self.is_running = True
        logger.info("🤖 Autonomous Agent started - Continuous monitoring enabled")
        
        while self.is_running:
            try:
                # Create fresh session for each cycle
                async with AsyncSessionLocal() as db:
                    data_service = DataService(db)
                    toolkit = AgentToolkit(data_service)
                    
                    # Get all active tags
                    result = await db.execute(
                        select(Tag).where(Tag.is_active == True).limit(50)
                    )
                    tags = result.scalars().all()
                    
                    if not tags:
                        logger.warning("No active tags found for monitoring")
                        await asyncio.sleep(self.monitoring_interval)
                        continue
                    
                    # Run monitoring strategies sequentially (can't share session concurrently)
                    monitoring_methods = [
                        ("detect_anomalies", self.detect_anomalies),
                        ("analyze_performance", self.analyze_performance),
                        ("check_alarm_conditions", self.check_alarm_conditions),
                        ("identify_optimization_opportunities", self.identify_optimization_opportunities),
                        ("predict_future_states", self.predict_future_states),
                    ]
                    
                    for method_name, method in monitoring_methods:
                        try:
                            results = await method(tags, toolkit)
                            if results:
                                for insight in results:
                                    self.add_insight(insight)
                        except Exception as e:
                            logger.error(f"{method_name} failed: {e}")
                    
                    logger.info(f"✅ Monitoring cycle complete. Total insights: {len(self.insights)}")
                    
                await asyncio.sleep(self.monitoring_interval)
            except Exception as e:
                logger.error(f"Error in monitoring cycle: {e}")
                await asyncio.sleep(self.monitoring_interval)
    
    def stop(self):
        """Stop autonomous monitoring"""
        self.is_running = False
        logger.info("🛑 Autonomous Agent stopped")
    
    async def detect_anomalies(self, tags: List[Tag], toolkit: AgentToolkit) -> List[AutonomousInsight]:
        """Detect anomalies in tag data"""
        insights = []
        
        # Analyze critical tags for anomalies
        critical_tags = [tag for tag in tags if tag.category.value in ["process", "control"]][:10]
        
        for tag in critical_tags:
            try:
                # Use toolkit to detect anomalies
                result = await toolkit.execute_tool(
                    "detect_anomalies",
                    {
                        "tag_id": str(tag.id),
                        "duration": "1h",
                        "sensitivity": "medium"
                    }
                )
                
                if result.success and result.data.get("anomaly_count", 0) > 0:
                    anomalies = result.data["anomalies_detected"]
                    
                    insight = AutonomousInsight(
                        insight_id=f"anomaly_{tag.id}_{datetime.now().timestamp()}",
                        title=f"Anomalia detectada: {tag.name}",
                        description=f"Detectadas {len(anomalies)} anomalias na última hora. {result.data.get('insight', '')}",
                        category="anomaly",
                        severity=self._calculate_anomaly_severity(len(anomalies)),
                        tags=[str(tag.id)],
                        metrics={
                            "anomaly_count": len(anomalies),
                            "mean": result.data.get("statistics", {}).get("mean"),
                            "stddev": result.data.get("statistics", {}).get("stddev"),
                            "latest_anomaly": anomalies[0] if anomalies else None
                        },
                        recommendations=[
                            "Verificar sensor ou equipamento",
                            "Analisar condições de processo",
                            "Revisar histórico para padrões similares"
                        ],
                        timestamp=datetime.now(),
                        data=result.data
                    )
                    insights.append(insight)
                    
            except Exception as e:
                logger.error(f"Error detecting anomalies for tag {tag.id}: {e}")
        
        return insights
    
    async def analyze_performance(self, tags: List[Tag], toolkit: AgentToolkit) -> List[AutonomousInsight]:
        """Analyze equipment performance"""
        insights = []
        
        # Find speed/velocity tags for performance analysis
        speed_tags = [tag for tag in tags if "velocidade" in tag.name.lower() or "speed" in tag.name.lower()]
        
        for tag in speed_tags[:5]:
            try:
                # Get statistics
                result = await toolkit.execute_tool(
                    "calculate_statistics",
                    {
                        "tag_id": str(tag.id),
                        "duration": "24h"
                    }
                )
                
                if result.success:
                    stats = result.data
                    mean = stats.get("mean", 0)
                    
                    # Assume design speed is around 1200 RPM (you can make this configurable)
                    design_speed = 1200
                    performance = (mean / design_speed * 100) if design_speed > 0 else 0
                    
                    if performance < 80:
                        severity = "high"
                        title = f"Performance baixa: {tag.name}"
                        recs = [
                            "Verificar carga do equipamento",
                            "Inspecionar sistema de transmissão",
                            "Analisar consumo de energia"
                        ]
                    elif performance > 110:
                        severity = "medium"
                        title = f"Performance acima do esperado: {tag.name}"
                        recs = [
                            "Monitorar temperatura do motor",
                            "Verificar desgaste de componentes",
                            "Avaliar sustentabilidade da velocidade"
                        ]
                    else:
                        continue  # Normal performance, no insight needed
                    
                    insight = AutonomousInsight(
                        insight_id=f"performance_{tag.id}_{datetime.now().timestamp()}",
                        title=title,
                        description=f"Velocidade média: {mean:.0f} RPM ({performance:.1f}% do design). Variação: ±{stats.get('stddev', 0):.0f} RPM",
                        category="optimization",
                        severity=severity,
                        tags=[str(tag.id)],
                        metrics={
                            "mean": mean,
                            "design": design_speed,
                            "performance": performance,
                            "stddev": stats.get("stddev"),
                            "min": stats.get("min"),
                            "max": stats.get("max")
                        },
                        recommendations=recs,
                        timestamp=datetime.now(),
                        data=stats
                    )
                    insights.append(insight)
                    
            except Exception as e:
                logger.error(f"Error analyzing performance for tag {tag.id}: {e}")
        
        return insights
    
    async def check_alarm_conditions(self, tags: List[Tag], toolkit: AgentToolkit) -> List[AutonomousInsight]:
        """Check for alarm conditions and patterns"""
        insights = []
        
        # Find alarm tags
        alarm_tags = [tag for tag in tags if "alarm" in tag.name.lower() or "alarme" in tag.name.lower()]
        
        if alarm_tags:
            try:
                # Analyze alarm patterns
                result = await toolkit.execute_tool(
                    "analyze_alarm_patterns",
                    {
                        "alarm_tags": [str(tag.id) for tag in alarm_tags[:10]],
                        "duration": "24h"
                    }
                )
                
                if result.success:
                    data = result.data
                    total_alarms = data.get("total_alarm_count", 0)
                    
                    if total_alarms > 50:
                        insight = AutonomousInsight(
                            insight_id=f"alarm_flood_{datetime.now().timestamp()}",
                            title="Alto volume de alarmes detectado",
                            description=f"Total de {total_alarms} alarmes nas últimas 24h. {' '.join(data.get('insights', []))}",
                            category="alert",
                            severity="high" if total_alarms > 100 else "medium",
                            tags=[str(tag.id) for tag in alarm_tags],
                            metrics={
                                "total_alarms": total_alarms,
                                "patterns": data.get("patterns", [])
                            },
                            recommendations=data.get("insights", []),
                            timestamp=datetime.now(),
                            data=data
                        )
                        insights.append(insight)
                        
            except Exception as e:
                logger.error(f"Error analyzing alarm patterns: {e}")
        
        return insights
    
    async def identify_optimization_opportunities(self, tags: List[Tag], toolkit: AgentToolkit) -> List[AutonomousInsight]:
        """Identify opportunities for process optimization"""
        insights = []
        
        # Look for correlation opportunities between related tags
        # Group tags by equipment/area (simplified by name prefix)
        equipment_groups = {}
        for tag in tags:
            prefix = tag.name.split('_')[0] if '_' in tag.name else 'GENERAL'
            if prefix not in equipment_groups:
                equipment_groups[prefix] = []
            equipment_groups[prefix].append(tag)
        
        # Analyze groups with multiple tags
        for equipment, group_tags in list(equipment_groups.items())[:5]:
            if len(group_tags) >= 2:
                try:
                    # Compare tags in the group
                    result = await toolkit.execute_tool(
                        "compare_tags",
                        {
                            "tag_ids": [str(tag.id) for tag in group_tags[:5]],
                            "duration": "24h"
                        }
                    )
                    
                    if result.success and result.data.get("insights"):
                        insight = AutonomousInsight(
                            insight_id=f"optimization_{equipment}_{datetime.now().timestamp()}",
                            title=f"Oportunidade de otimização: {equipment}",
                            description=f"Análise de {result.data.get('tags_compared')} parâmetros. {result.data.get('summary')}",
                            category="optimization",
                            severity="info",
                            tags=[str(tag.id) for tag in group_tags],
                            metrics=result.data.get("statistics", {}),
                            recommendations=[
                                "Analisar correlações entre parâmetros",
                                "Buscar oportunidades de ajuste fino",
                                "Considerar automação de controle"
                            ],
                            timestamp=datetime.now(),
                            data=result.data
                        )
                        insights.append(insight)
                        
                except Exception as e:
                    logger.error(f"Error analyzing equipment group {equipment}: {e}")
        
        return insights
    
    async def predict_future_states(self, tags: List[Tag], toolkit: AgentToolkit) -> List[AutonomousInsight]:
        """Predict future states and generate predictive insights"""
        insights = []
        
        # Find level/inventory tags for predictive analysis
        level_tags = [tag for tag in tags if "nivel" in tag.name.lower() or "level" in tag.name.lower() or "inventario" in tag.name.lower()]
        
        for tag in level_tags[:3]:
            try:
                # Get historical data
                result = await toolkit.execute_tool(
                    "get_historical_data",
                    {
                        "tag_id": str(tag.id),
                        "duration": "24h"
                    }
                )
                
                if result.success and result.data.get("points"):
                    points = result.data["points"]
                    
                    # Simple linear trend calculation
                    if len(points) >= 10:
                        first_value = points[0].get("value", 0)
                        last_value = points[-1].get("value", 0)
                        change = last_value - first_value
                        rate = change / 24  # Change per hour
                        
                        # Predict time to reach limits (assuming 0-100 scale)
                        if rate > 0.5:  # Increasing
                            hours_to_full = (100 - last_value) / rate if rate > 0 else float('inf')
                            if hours_to_full < 24:
                                insight = AutonomousInsight(
                                    insight_id=f"prediction_{tag.id}_{datetime.now().timestamp()}",
                                    title=f"Previsão: {tag.name} atingirá capacidade máxima",
                                    description=f"Nível atual: {last_value:.1f}%. Taxa de enchimento: {rate:.2f}%/h. Tempo estimado até capacidade máxima: {hours_to_full:.1f} horas",
                                    category="prediction",
                                    severity="medium" if hours_to_full < 8 else "low",
                                    tags=[str(tag.id)],
                                    metrics={
                                        "current_level": last_value,
                                        "rate": rate,
                                        "hours_to_full": hours_to_full,
                                        "predicted_time": (datetime.now() + timedelta(hours=hours_to_full)).isoformat()
                                    },
                                    recommendations=[
                                        "Planejar esvaziamento ou parada de enchimento",
                                        "Verificar capacidade de processamento downstream",
                                        "Ajustar taxa de alimentação se necessário"
                                    ],
                                    timestamp=datetime.now(),
                                    data={"trend": "increasing", "rate": rate}
                                )
                                insights.append(insight)
                        
                        elif rate < -0.5:  # Decreasing
                            hours_to_empty = last_value / abs(rate) if rate < 0 else float('inf')
                            if hours_to_empty < 24:
                                insight = AutonomousInsight(
                                    insight_id=f"prediction_{tag.id}_{datetime.now().timestamp()}",
                                    title=f"Previsão: {tag.name} atingirá nível baixo",
                                    description=f"Nível atual: {last_value:.1f}%. Taxa de esvaziamento: {abs(rate):.2f}%/h. Tempo estimado até nível baixo: {hours_to_empty:.1f} horas",
                                    category="prediction",
                                    severity="medium" if hours_to_empty < 8 else "low",
                                    tags=[str(tag.id)],
                                    metrics={
                                        "current_level": last_value,
                                        "rate": rate,
                                        "hours_to_empty": hours_to_empty,
                                        "predicted_time": (datetime.now() + timedelta(hours=hours_to_empty)).isoformat()
                                    },
                                    recommendations=[
                                        "Planejar reabastecimento",
                                        "Verificar disponibilidade de material",
                                        "Alertar equipe de logística"
                                    ],
                                    timestamp=datetime.now(),
                                    data={"trend": "decreasing", "rate": rate}
                                )
                                insights.append(insight)
                        
            except Exception as e:
                logger.error(f"Error predicting for tag {tag.id}: {e}")
        
        return insights
    
    def _calculate_anomaly_severity(self, anomaly_count: int) -> str:
        """Calculate severity based on anomaly count"""
        if anomaly_count >= 10:
            return "critical"
        elif anomaly_count >= 5:
            return "high"
        elif anomaly_count >= 2:
            return "medium"
        else:
            return "low"
    
    def add_insight(self, insight: AutonomousInsight):
        """Add insight to the feed"""
        self.insights.insert(0, insight)  # Add to beginning
        
        # Keep only max_insights
        if len(self.insights) > self.max_insights:
            self.insights = self.insights[:self.max_insights]
        
        logger.info(f"📝 New insight: [{insight.severity}] {insight.title}")
    
    def get_insights(
        self,
        category: Optional[str] = None,
        severity: Optional[str] = None,
        limit: int = 20
    ) -> List[Dict[str, Any]]:
        """Get insights with optional filters"""
        filtered = self.insights
        
        if category:
            filtered = [i for i in filtered if i.category == category]
        
        if severity:
            filtered = [i for i in filtered if i.severity == severity]
        
        return [i.to_dict() for i in filtered[:limit]]
    
    def get_dashboard_summary(self) -> Dict[str, Any]:
        """Get summary for dashboard"""
        total = len(self.insights)
        
        by_category = {}
        by_severity = {}
        
        for insight in self.insights:
            by_category[insight.category] = by_category.get(insight.category, 0) + 1
            by_severity[insight.severity] = by_severity.get(insight.severity, 0) + 1
        
        return {
            "total_insights": total,
            "by_category": by_category,
            "by_severity": by_severity,
            "latest_insight": self.insights[0].to_dict() if self.insights else None,
            "monitoring_active": self.is_running,
            "monitoring_interval": self.monitoring_interval
        }


# Global agent instance (will be initialized on startup)
_autonomous_agent: Optional[AutonomousAgent] = None


async def init_autonomous_agent():
    """Initialize autonomous agent"""
    global _autonomous_agent
    _autonomous_agent = AutonomousAgent()
    # Start monitoring in background
    asyncio.create_task(_autonomous_agent.start())
    logger.info("✅ Autonomous Agent initialized and started")


def get_autonomous_agent() -> Optional[AutonomousAgent]:
    """Get autonomous agent instance"""
    return _autonomous_agent
