"""
Autonomous AI Agent Service - Continuous Process Monitoring

This service runs continuously to:
- Monitor process in real-time
- Detect anomalies and patterns
- Generate proactive insights
- Suggest improvements and optimizations
- Alert on critical conditions
"""

import asyncio
import logging
from datetime import datetime, timedelta
from typing import List, Dict, Any, Optional
from sqlalchemy.ext.asyncio import AsyncSession
from sqlalchemy import select
import json

from app.models.tag import Tag
from app.models.asset import Asset
from app.services.data_service import DataService
from app.services.agent_tools import AgentToolkit
from app.services.asset_health import AssetHealthCalculator
from app.services.asset_health_alert_manager import AssetHealthAlertManager
from app.services.asset_health_analytics import AssetHealthAnalytics
from app.services.influxdb import influxdb_service
from app.services.pareto_analyzer import ParetoAnalyzer

logger = logging.getLogger(__name__)


def convert_numpy_types(obj):
    """
    Recursively convert numpy types to Python native types for JSON serialization.

    This fixes the 'Unable to serialize unknown type: numpy.bool_' error.
    """
    import numpy as np

    if isinstance(obj, dict):
        return {key: convert_numpy_types(value) for key, value in obj.items()}
    elif isinstance(obj, list):
        return [convert_numpy_types(item) for item in obj]
    elif isinstance(obj, (np.bool_, np.bool8)):
        return bool(obj)
    elif isinstance(obj, (np.integer, np.int64, np.int32)):
        return int(obj)
    elif isinstance(obj, (np.floating, np.float64, np.float32)):
        return float(obj)
    elif isinstance(obj, np.ndarray):
        return obj.tolist()
    else:
        return obj


class AutonomousInsight:
    """Represents an autonomous insight generated by the agent"""
    
    def __init__(
        self,
        insight_id: str,
        title: str,
        description: str,
        category: str,  # anomaly, optimization, alert, trend, prediction
        severity: str,  # critical, high, medium, low, info
        tags: List[str],
        metrics: Dict[str, Any],
        recommendations: List[str],
        timestamp: datetime,
        data: Optional[Dict[str, Any]] = None
    ):
        self.insight_id = insight_id
        self.title = title
        self.description = description
        self.category = category
        self.severity = severity
        self.tags = tags
        self.metrics = metrics
        self.recommendations = recommendations
        self.timestamp = timestamp
        self.data = data or {}
    
    def to_dict(self) -> Dict[str, Any]:
        # Convert numpy types to Python native types to avoid serialization errors
        return convert_numpy_types({
            "id": self.insight_id,
            "title": self.title,
            "description": self.description,
            "category": self.category,
            "severity": self.severity,
            "tags": self.tags,
            "metrics": self.metrics,
            "recommendations": self.recommendations,
            "timestamp": self.timestamp.isoformat(),
            "data": self.data
        })


class AutonomousAgent:
    """
    Autonomous AI Agent for continuous process monitoring
    
    This agent runs in the background, constantly monitoring the process
    and generating insights without user intervention.
    """
    
    def __init__(self):
        self.insights: List[AutonomousInsight] = []
        self.max_insights = 100  # Keep last 100 insights
        self.monitoring_interval = 60  # Monitor every 60 seconds
        self.is_running = False
        
    async def start(self):
        """Start autonomous monitoring"""
        from app.db.session import AsyncSessionLocal
        
        self.is_running = True
        logger.info("🤖 Autonomous Agent started - Continuous monitoring enabled")
        
        while self.is_running:
            try:
                # Create fresh session for each cycle
                async with AsyncSessionLocal() as db:
                    data_service = DataService(db)
                    toolkit = AgentToolkit(data_service)

                    # AUTO-DISCOVERY: Get all tags from InfluxDB (single source of truth)
                    tag_names = influxdb_service.list_all_measurements()

                    if not tag_names:
                        logger.warning("⚠️  No tags found in InfluxDB for monitoring")
                        await asyncio.sleep(self.monitoring_interval)
                        continue

                    logger.info(f"🔍 Auto-discovered {len(tag_names)} tags from InfluxDB: {', '.join(tag_names[:5])}{'...' if len(tag_names) > 5 else ''}")

                    # Get tag metadata from PostgreSQL if available (optional enrichment)
                    # This provides additional context like category, min/max values
                    result = await db.execute(
                        select(Tag).where(Tag.name.in_(tag_names))
                    )
                    tag_metadata_map = {tag.name: tag for tag in result.scalars().all()}

                    # Create lightweight tag objects for discovered tags
                    # If metadata exists in PostgreSQL, use it; otherwise use defaults
                    tags = []
                    for tag_name in tag_names[:50]:  # Limit to 50 tags per cycle
                        if tag_name in tag_metadata_map:
                            # Use existing metadata from PostgreSQL
                            tags.append(tag_metadata_map[tag_name])
                        else:
                            # Create lightweight tag object for monitoring
                            # (no database persistence, just for analysis)
                            from app.models.tag import TagCategory, TagDataType
                            import uuid
                            lightweight_tag = type('Tag', (), {
                                'id': uuid.uuid4(),  # Generate temporary UUID
                                'name': tag_name,
                                'tag_address': tag_name,
                                'description': f'Auto-discovered tag: {tag_name}',
                                'category': TagCategory.PROCESS,
                                'data_type': TagDataType.FLOAT,
                                'is_active': True,
                                'min_value': None,
                                'max_value': None,
                                'unit': '',
                                'device_id': None,
                            })()
                            tags.append(lightweight_tag)
                    
                    # Run monitoring strategies sequentially (all using same session to avoid nested sessions)
                    monitoring_methods = [
                        ("detect_anomalies", self.detect_anomalies),
                        ("analyze_performance", self.analyze_performance),
                        ("check_alarm_conditions", self.check_alarm_conditions),
                        ("monitor_asset_health", self.monitor_asset_health),
                        ("identify_optimization_opportunities", self.identify_optimization_opportunities),
                        ("predict_future_states", self.predict_future_states),
                        ("generate_quality_insights", self.generate_quality_insights),
                    ]

                    for method_name, method in monitoring_methods:
                        try:
                            results = await method(tags, toolkit, db)  # Pass db session to avoid nested sessions
                            if results:
                                for insight in results:
                                    self.add_insight(insight)
                        except Exception as e:
                            logger.error(f"{method_name} failed: {e}")

                    # Monitor ML/DS insights (separate from tag-based monitoring)
                    try:
                        ml_insights = await self.monitor_ml_insights(db)
                        if ml_insights:
                            for insight in ml_insights:
                                self.add_insight(insight)
                            logger.info(f"✅ Added {len(ml_insights)} ML insights to autonomous agent")
                    except Exception as e:
                        logger.error(f"monitor_ml_insights failed: {e}")
                    
                    logger.info(f"✅ Monitoring cycle complete. Total insights: {len(self.insights)}")
                    
                await asyncio.sleep(self.monitoring_interval)
            except Exception as e:
                logger.error(f"Error in monitoring cycle: {e}")
                await asyncio.sleep(self.monitoring_interval)
    
    def stop(self):
        """Stop autonomous monitoring"""
        self.is_running = False
        logger.info("🛑 Autonomous Agent stopped")
    
    async def detect_anomalies(self, tags: List[Tag], toolkit: AgentToolkit, db: AsyncSession) -> List[AutonomousInsight]:
        """Detect anomalies in tag data"""
        insights = []
        
        # Analyze critical tags for anomalies
        critical_tags = [tag for tag in tags if tag.category.value in ["process", "control"]][:10]
        
        for tag in critical_tags:
            try:
                # Use toolkit to detect anomalies
                result = await toolkit.execute_tool(
                    "detect_anomalies",
                    {
                        "tag_id": str(tag.id),
                        "duration": "1h",
                        "sensitivity": "medium"
                    }
                )
                
                if result.success and result.data.get("anomaly_count", 0) > 0:
                    anomalies = result.data["anomalies_detected"]
                    
                    insight = AutonomousInsight(
                        insight_id=f"anomaly_{tag.id}_{datetime.now().timestamp()}",
                        title=f"Anomalia detectada: {tag.name}",
                        description=f"Detectadas {len(anomalies)} anomalias na última hora. {result.data.get('insight', '')}",
                        category="anomaly",
                        severity=self._calculate_anomaly_severity(len(anomalies)),
                        tags=[str(tag.id)],
                        metrics={
                            "anomaly_count": len(anomalies),
                            "mean": result.data.get("statistics", {}).get("mean"),
                            "stddev": result.data.get("statistics", {}).get("stddev"),
                            "latest_anomaly": anomalies[0] if anomalies else None
                        },
                        recommendations=[
                            "Verificar sensor ou equipamento",
                            "Analisar condições de processo",
                            "Revisar histórico para padrões similares"
                        ],
                        timestamp=datetime.now(),
                        data=result.data
                    )
                    insights.append(insight)
                    
            except Exception as e:
                logger.error(f"Error detecting anomalies for tag {tag.id}: {e}")
        
        return insights
    
    async def analyze_performance(self, tags: List[Tag], toolkit: AgentToolkit, db: AsyncSession) -> List[AutonomousInsight]:
        """Analyze equipment performance"""
        insights = []
        
        # Find speed/velocity tags for performance analysis
        speed_tags = [tag for tag in tags if "velocidade" in tag.name.lower() or "speed" in tag.name.lower()]
        
        for tag in speed_tags[:5]:
            try:
                # Get statistics
                result = await toolkit.execute_tool(
                    "calculate_statistics",
                    {
                        "tag_id": str(tag.id),
                        "duration": "24h"
                    }
                )
                
                if result.success:
                    stats = result.data
                    mean = stats.get("mean", 0)
                    
                    # Assume design speed is around 1200 RPM (you can make this configurable)
                    design_speed = 1200
                    performance = (mean / design_speed * 100) if design_speed > 0 else 0
                    
                    if performance < 80:
                        severity = "high"
                        title = f"Performance baixa: {tag.name}"
                        recs = [
                            "Verificar carga do equipamento",
                            "Inspecionar sistema de transmissão",
                            "Analisar consumo de energia"
                        ]
                    elif performance > 110:
                        severity = "medium"
                        title = f"Performance acima do esperado: {tag.name}"
                        recs = [
                            "Monitorar temperatura do motor",
                            "Verificar desgaste de componentes",
                            "Avaliar sustentabilidade da velocidade"
                        ]
                    else:
                        continue  # Normal performance, no insight needed
                    
                    insight = AutonomousInsight(
                        insight_id=f"performance_{tag.id}_{datetime.now().timestamp()}",
                        title=title,
                        description=f"Velocidade média: {mean:.0f} RPM ({performance:.1f}% do design). Variação: ±{stats.get('stddev', 0):.0f} RPM",
                        category="optimization",
                        severity=severity,
                        tags=[str(tag.id)],
                        metrics={
                            "mean": mean,
                            "design": design_speed,
                            "performance": performance,
                            "stddev": stats.get("stddev"),
                            "min": stats.get("min"),
                            "max": stats.get("max")
                        },
                        recommendations=recs,
                        timestamp=datetime.now(),
                        data=stats
                    )
                    insights.append(insight)
                    
            except Exception as e:
                logger.error(f"Error analyzing performance for tag {tag.id}: {e}")
        
        return insights
    
    async def check_alarm_conditions(self, tags: List[Tag], toolkit: AgentToolkit, db: AsyncSession) -> List[AutonomousInsight]:
        """Check for alarm conditions and patterns"""
        insights = []
        
        # Find alarm tags
        alarm_tags = [tag for tag in tags if "alarm" in tag.name.lower() or "alarme" in tag.name.lower()]
        
        if alarm_tags:
            try:
                # Analyze alarm patterns
                result = await toolkit.execute_tool(
                    "analyze_alarm_patterns",
                    {
                        "alarm_tags": [str(tag.id) for tag in alarm_tags[:10]],
                        "duration": "24h"
                    }
                )
                
                if result.success:
                    data = result.data
                    total_alarms = data.get("total_alarm_count", 0)
                    
                    if total_alarms > 50:
                        insight = AutonomousInsight(
                            insight_id=f"alarm_flood_{datetime.now().timestamp()}",
                            title="Alto volume de alarmes detectado",
                            description=f"Total de {total_alarms} alarmes nas últimas 24h. {' '.join(data.get('insights', []))}",
                            category="alert",
                            severity="high" if total_alarms > 100 else "medium",
                            tags=[str(tag.id) for tag in alarm_tags],
                            metrics={
                                "total_alarms": total_alarms,
                                "patterns": data.get("patterns", [])
                            },
                            recommendations=data.get("insights", []),
                            timestamp=datetime.now(),
                            data=data
                        )
                        insights.append(insight)
                        
            except Exception as e:
                logger.error(f"Error analyzing alarm patterns: {e}")
        
        return insights
    
    async def identify_optimization_opportunities(self, tags: List[Tag], toolkit: AgentToolkit, db: AsyncSession) -> List[AutonomousInsight]:
        """Identify opportunities for process optimization"""
        insights = []
        
        # Look for correlation opportunities between related tags
        # Group tags by equipment/area (simplified by name prefix)
        equipment_groups = {}
        for tag in tags:
            prefix = tag.name.split('_')[0] if '_' in tag.name else 'GENERAL'
            if prefix not in equipment_groups:
                equipment_groups[prefix] = []
            equipment_groups[prefix].append(tag)
        
        # Analyze groups with multiple tags
        for equipment, group_tags in list(equipment_groups.items())[:5]:
            if len(group_tags) >= 2:
                try:
                    # Compare tags in the group
                    result = await toolkit.execute_tool(
                        "compare_tags",
                        {
                            "tag_ids": [str(tag.id) for tag in group_tags[:5]],
                            "duration": "24h"
                        }
                    )
                    
                    if result.success and result.data.get("insights"):
                        insight = AutonomousInsight(
                            insight_id=f"optimization_{equipment}_{datetime.now().timestamp()}",
                            title=f"Oportunidade de otimização: {equipment}",
                            description=f"Análise de {result.data.get('tags_compared')} parâmetros. {result.data.get('summary')}",
                            category="optimization",
                            severity="info",
                            tags=[str(tag.id) for tag in group_tags],
                            metrics=result.data.get("statistics", {}),
                            recommendations=[
                                "Analisar correlações entre parâmetros",
                                "Buscar oportunidades de ajuste fino",
                                "Considerar automação de controle"
                            ],
                            timestamp=datetime.now(),
                            data=result.data
                        )
                        insights.append(insight)
                        
                except Exception as e:
                    logger.error(f"Error analyzing equipment group {equipment}: {e}")
        
        return insights
    
    async def predict_future_states(self, tags: List[Tag], toolkit: AgentToolkit, db: AsyncSession) -> List[AutonomousInsight]:
        """Predict future states and generate predictive insights"""
        insights = []
        
        # Find level/inventory tags for predictive analysis
        level_tags = [tag for tag in tags if "nivel" in tag.name.lower() or "level" in tag.name.lower() or "inventario" in tag.name.lower()]
        
        for tag in level_tags[:3]:
            try:
                # Get historical data
                result = await toolkit.execute_tool(
                    "get_historical_data",
                    {
                        "tag_id": str(tag.id),
                        "duration": "24h"
                    }
                )
                
                if result.success and result.data.get("points"):
                    points = result.data["points"]
                    
                    # Simple linear trend calculation
                    if len(points) >= 10:
                        first_value = points[0].get("value", 0)
                        last_value = points[-1].get("value", 0)
                        change = last_value - first_value
                        rate = change / 24  # Change per hour
                        
                        # Predict time to reach limits (assuming 0-100 scale)
                        if rate > 0.5:  # Increasing
                            hours_to_full = (100 - last_value) / rate if rate > 0 else float('inf')
                            if hours_to_full < 24:
                                insight = AutonomousInsight(
                                    insight_id=f"prediction_{tag.id}_{datetime.now().timestamp()}",
                                    title=f"Previsão: {tag.name} atingirá capacidade máxima",
                                    description=f"Nível atual: {last_value:.1f}%. Taxa de enchimento: {rate:.2f}%/h. Tempo estimado até capacidade máxima: {hours_to_full:.1f} horas",
                                    category="prediction",
                                    severity="medium" if hours_to_full < 8 else "low",
                                    tags=[str(tag.id)],
                                    metrics={
                                        "current_level": last_value,
                                        "rate": rate,
                                        "hours_to_full": hours_to_full,
                                        "predicted_time": (datetime.now() + timedelta(hours=hours_to_full)).isoformat()
                                    },
                                    recommendations=[
                                        "Planejar esvaziamento ou parada de enchimento",
                                        "Verificar capacidade de processamento downstream",
                                        "Ajustar taxa de alimentação se necessário"
                                    ],
                                    timestamp=datetime.now(),
                                    data={"trend": "increasing", "rate": rate}
                                )
                                insights.append(insight)
                        
                        elif rate < -0.5:  # Decreasing
                            hours_to_empty = last_value / abs(rate) if rate < 0 else float('inf')
                            if hours_to_empty < 24:
                                insight = AutonomousInsight(
                                    insight_id=f"prediction_{tag.id}_{datetime.now().timestamp()}",
                                    title=f"Previsão: {tag.name} atingirá nível baixo",
                                    description=f"Nível atual: {last_value:.1f}%. Taxa de esvaziamento: {abs(rate):.2f}%/h. Tempo estimado até nível baixo: {hours_to_empty:.1f} horas",
                                    category="prediction",
                                    severity="medium" if hours_to_empty < 8 else "low",
                                    tags=[str(tag.id)],
                                    metrics={
                                        "current_level": last_value,
                                        "rate": rate,
                                        "hours_to_empty": hours_to_empty,
                                        "predicted_time": (datetime.now() + timedelta(hours=hours_to_empty)).isoformat()
                                    },
                                    recommendations=[
                                        "Planejar reabastecimento",
                                        "Verificar disponibilidade de material",
                                        "Alertar equipe de logística"
                                    ],
                                    timestamp=datetime.now(),
                                    data={"trend": "decreasing", "rate": rate}
                                )
                                insights.append(insight)
                        
            except Exception as e:
                logger.error(f"Error predicting for tag {tag.id}: {e}")
        
        return insights

    async def monitor_asset_health(self, tags: List[Tag], toolkit: AgentToolkit, db: AsyncSession) -> List[AutonomousInsight]:
        """Monitor asset health scores and generate insights for problematic assets"""
        insights = []

        try:
            # Get all active assets with attributes (using session passed as parameter)
            result = await db.execute(
                select(Asset).where(Asset.is_active == True)
            )
            assets = result.scalars().all()

            if not assets:
                return insights

            # Initialize health calculator, alert manager, and analytics
            health_calculator = AssetHealthCalculator(db)
            alert_manager = AssetHealthAlertManager(db)
            analytics = AssetHealthAnalytics(db)

            # Check health for assets with attributes
            for asset in assets:
                try:
                    # Get attributes count from the asset
                    from app.models.asset_attribute import AssetAttribute
                    attr_result = await db.execute(
                        select(AssetAttribute).where(AssetAttribute.asset_id == asset.id)
                    )
                    attributes = attr_result.scalars().all()

                    if not attributes:
                        continue  # Skip assets without attributes

                    # Calculate health score
                    health_data = await health_calculator.calculate_asset_health(str(asset.id))

                    health_score = health_data.get("health_score", 100)
                    status = health_data.get("status", "unknown")
                    issues = health_data.get("issues", [])
                    warnings = health_data.get("warnings", [])

                    # Generate insights based on health status
                    severity_mapping = {
                        "critical": "critical",
                        "poor": "high",
                        "fair": "medium",
                        "good": "low",
                        "excellent": "info"
                    }

                    # Only create insights for problematic assets (critical, poor, fair)
                    if status in ["critical", "poor", "fair"]:
                        # Build description
                        problems = []
                        if issues:
                            problems.append(f"{len(issues)} problemas críticos")
                        if warnings:
                            problems.append(f"{len(warnings)} avisos")

                        problems_str = " e ".join(problems) if problems else "Parâmetros fora dos limites recomendados"

                        # Build recommendations
                        recommendations = []
                        if issues:
                            recommendations.append("🔴 Ação imediata necessária para problemas críticos")
                            for issue in issues[:3]:  # Top 3 issues
                                attr_name = issue.get("attribute", {}).get("name", "Unknown")
                                recommendations.append(f"  • Verificar: {attr_name}")

                        if warnings:
                            recommendations.append("⚠️ Monitorar avisos atentamente")
                            for warning in warnings[:2]:  # Top 2 warnings
                                attr_name = warning.get("attribute", {}).get("name", "Unknown")
                                recommendations.append(f"  • Atenção em: {attr_name}")

                        if not recommendations:
                            recommendations = [
                                "Revisar configuração de thresholds dos atributos",
                                "Verificar condições operacionais do asset",
                                "Considerar manutenção preventiva"
                            ]

                        # Create insight
                        insight = AutonomousInsight(
                            insight_id=f"asset_health_{asset.id}_{datetime.now().timestamp()}",
                            title=f"⚠️ Asset com saúde {status.upper()}: {asset.name}",
                            description=f"Score de saúde: {health_score:.1f}/100. {problems_str}. Tipo: {asset.asset_type.value}.",
                            category="alert",
                            severity=severity_mapping.get(status, "medium"),
                            tags=[],  # No specific tags, this is asset-level
                            metrics={
                                "asset_id": str(asset.id),
                                "asset_name": asset.name,
                                "asset_type": asset.asset_type.value,
                                "health_score": health_score,
                                "status": status,
                                "issues_count": len(issues),
                                "warnings_count": len(warnings),
                                "attributes_count": len(attributes)
                            },
                            recommendations=recommendations,
                            timestamp=datetime.now(),
                            data={
                                "asset_id": str(asset.id),
                                "full_path": asset.full_path,
                                "issues": issues[:5],  # First 5 issues
                                "warnings": warnings[:5],  # First 5 warnings
                                "health_details": health_data
                            }
                        )
                        insights.append(insight)

                        logger.info(
                            f"🏥 Asset Health Alert: {asset.name} - "
                            f"Score: {health_score:.1f} ({status}), "
                            f"Issues: {len(issues)}, Warnings: {len(warnings)}"
                        )

                        # Create automated alert
                        try:
                            await alert_manager.check_and_create_alerts(str(asset.id))
                        except Exception as alert_error:
                            logger.error(f"Error creating alert for asset {asset.id}: {alert_error}")

                    # Record health snapshot for trend analysis (for all assets, not just problematic ones)
                    try:
                        await analytics.record_health_snapshot(str(asset.id))
                    except Exception as snapshot_error:
                        logger.error(f"Error recording health snapshot for asset {asset.id}: {snapshot_error}")

                except Exception as e:
                    logger.error(f"Error checking health for asset {asset.id}: {e}")
                    continue

        except Exception as e:
            logger.error(f"Error in monitor_asset_health: {e}")

        return insights

    async def monitor_ml_insights(self, db: AsyncSession) -> List[AutonomousInsight]:
        """
        Monitora insights ML/DS e gera alertas proativos

        Verifica:
        - Alertas críticos de MTBF/MTTR
        - Consumo energético anormal
        - Anomalias detectadas
        - Oportunidades de economia

        Returns:
            Lista de insights gerados
        """
        insights = []

        try:
            from app.services.agent_ml_integration import agent_ml_integration
            from app.models.organization import Organization
            from sqlalchemy import select

            # Get first organization (in multi-tenant system, this would be per-user)
            result = await db.execute(select(Organization).limit(1))
            organization = result.scalar_one_or_none()

            if not organization:
                logger.warning("No organization found for ML monitoring")
                return []

            organization_id = str(organization.id)

            # Verificar alertas críticos ML
            critical_alerts = await agent_ml_integration.check_critical_alerts(
                db=db,
                organization_id=organization_id
            )
            
            # ✨ NOVO: Obter resumo de anomalias detectadas pelo modelo ML treinado
            anomalies_summary = await agent_ml_integration.get_recent_anomalies_summary(hours=24)
            
            if anomalies_summary.get("status") == "success" and anomalies_summary.get("total_anomalies", 0) > 0:
                # Criar insight de anomalias ML
                total_anomalies = anomalies_summary["total_anomalies"]
                anomaly_rate = anomalies_summary["anomaly_rate"]
                model_used = anomalies_summary["model_used"]
                top_tags = anomalies_summary.get("top_problematic_tags", [])
                
                # Determinar severidade baseado na taxa de anomalias
                if anomaly_rate > 0.05:  # >5% de anomalias
                    severity = "high"
                elif anomaly_rate > 0.02:  # >2% de anomalias
                    severity = "medium"
                else:
                    severity = "low"
                
                # Construir descrição com top tags problemáticas
                top_tags_desc = ""
                if top_tags:
                    top_tags_desc = " Tags mais afetadas: " + ", ".join([
                        f"{t['tag_id']} ({t['anomaly_count']} anomalias, score máx: {t['max_score']:.2f})"
                        for t in top_tags[:3]
                    ])
                
                recommendations = [
                    f"Investigar {total_anomalies} anomalias detectadas pelo modelo {model_used}",
                    "Verificar condições operacionais durante os picos de anomalia",
                    "Analisar correlação com alarmes e eventos de manutenção"
                ]
                
                if top_tags:
                    recommendations.append(f"Priorizar investigação em: {', '.join([t['tag_id'] for t in top_tags[:3]])}")
                
                anomaly_insight = AutonomousInsight(
                    insight_id=f"ml_anomalies_{datetime.now().timestamp()}",
                    title=f"🤖 Anomalias ML Detectadas: {total_anomalies} pontos anormais (últimas 24h)",
                    description=f"Modelo {model_used} detectou {total_anomalies} anomalias em {anomalies_summary['total_points_analyzed']} pontos analisados (taxa: {anomaly_rate*100:.2f}%).{top_tags_desc}",
                    category="anomaly",
                    severity=severity,
                    tags=['ml', 'anomaly_detection', model_used],
                    metrics={
                        "total_anomalies": total_anomalies,
                        "anomaly_rate": anomaly_rate,
                        "model_used": model_used,
                        "points_analyzed": anomalies_summary["total_points_analyzed"],
                        "time_range_hours": anomalies_summary["time_range_hours"]
                    },
                    recommendations=recommendations,
                    timestamp=datetime.now(),
                    data={
                        "anomalies_by_tag": anomalies_summary.get("anomalies_by_tag", {}),
                        "top_problematic_tags": top_tags
                    }
                )
                
                insights.append(anomaly_insight)
                
                logger.info(
                    f"🤖 ML Anomaly Detection: {total_anomalies} anomalies found "
                    f"({anomaly_rate*100:.2f}% rate) using {model_used}"
                )

            # Gerar insights para cada alerta crítico
            for alert in critical_alerts:
                try:
                    # Mapear prioridade para severidade
                    severity_map = {
                        'high': 'critical',
                        'medium': 'high',
                        'low': 'medium'
                    }
                    severity = severity_map.get(alert['priority'], 'medium')

                    # Criar recomendações baseadas no tipo de alerta
                    recommendations = []
                    if alert['type'] == 'maintenance_critical':
                        recommendations = [
                            f"Agendar manutenção preventiva urgente para {alert.get('equipment_id', 'equipamento')}",
                            "Verificar histórico de falhas e padrões de degradação",
                            "Considerar substituição se manutenções forem frequentes"
                        ]
                    elif alert['type'] == 'energy_abnormal':
                        recommendations = [
                            "Investigar causa do consumo energético anormal",
                            "Verificar eficiência dos equipamentos",
                            "Revisar parâmetros operacionais e setpoints"
                        ]
                    elif alert['type'] == 'anomalies_multiple':
                        recommendations = [
                            "Investigar anomalias detectadas nas últimas 24h",
                            "Verificar se há padrão comum entre anomalias",
                            "Analisar condições operacionais durante anomalias"
                        ]

                    # Criar insight
                    insight = AutonomousInsight(
                        insight_id=f"ml_alert_{alert['type']}_{datetime.now().timestamp()}",
                        title=f"🤖 ML Alert: {alert['message']}",
                        description=f"Alerta ML/DS detectado. Tipo: {alert['type']}. Ação: {alert.get('action', 'investigar')}",
                        category="prediction",
                        severity=severity,
                        tags=['ml', 'predictive', alert['type']],
                        metrics={
                            "alert_type": alert['type'],
                            "priority": alert['priority'],
                            "action": alert.get('action', 'investigate'),
                        },
                        recommendations=recommendations,
                        timestamp=datetime.now(),
                        data=alert.get('details', {})
                    )

                    insights.append(insight)

                    logger.info(
                        f"🤖 ML Alert generated: {alert['type']} - "
                        f"Priority: {alert['priority']}, Message: {alert['message']}"
                    )

                except Exception as e:
                    logger.error(f"Error creating ML insight from alert: {e}")
                    continue

            # Log resumo
            if insights:
                logger.info(f"✅ Generated {len(insights)} ML insights from {len(critical_alerts)} critical alerts")
            else:
                logger.debug("No critical ML alerts at this time")

        except Exception as e:
            logger.error(f"Error in monitor_ml_insights: {e}")
            import traceback
            logger.error(traceback.format_exc())

        return insights

    def _calculate_anomaly_severity(self, anomaly_count: int) -> str:
        """Calculate severity based on anomaly count"""
        if anomaly_count >= 10:
            return "critical"
        elif anomaly_count >= 5:
            return "high"
        elif anomaly_count >= 2:
            return "medium"
        else:
            return "low"
    
    async def generate_quality_insights(self, tags: List[Tag], toolkit: AgentToolkit, db: AsyncSession) -> List[AutonomousInsight]:
        """
        Generate quality-based insights using quality tools (Pareto, SPC, etc.)

        This method integrates quality management tools to provide actionable insights:
        - Pareto Analysis: Identify vital few issues causing most problems (80/20 rule)
        - Statistical Process Control: Detect process variations
        - Root Cause Analysis: Understand failure patterns
        """
        insights = []

        try:
            # 1. PARETO ANALYSIS - Find top issues causing most problems
            logger.info("🎯 Running Pareto Analysis for quality insights...")
            pareto_analyzer = ParetoAnalyzer(db)

            # Analyze failures over last 7 days
            pareto_result = await pareto_analyzer.generate_pareto(days=7, min_occurrences=1)

            if pareto_result.get("status") == "success" and pareto_result.get("items"):
                items = pareto_result["items"]
                vital_few = [item for item in items if item.get("is_vital_few", False)]

                if vital_few:
                    # Generate insight for Pareto vital few
                    top_3 = vital_few[:3]
                    total_percentage = sum(item["percentage"] for item in top_3)

                    insight = AutonomousInsight(
                        insight_id=f"quality_pareto_{datetime.now().timestamp()}",
                        title=f"🎯 Pareto: {len(top_3)} problemas causam {total_percentage:.1f}% das falhas",
                        description=(
                            f"Análise Pareto identificou que {len(vital_few)} tipos de falha causam 80% dos problemas. "
                            f"Focar nos top 3 pode reduzir {total_percentage:.1f}% das falhas totais."
                        ),
                        category="optimization",
                        severity="medium",
                        tags=["pareto", "quality", "80-20"],
                        metrics={
                            "total_failure_types": len(items),
                            "vital_few_count": len(vital_few),
                            "vital_few_percentage": pareto_result.get("vital_few_percentage", 0),
                            "top_3_issues": [
                                {
                                    "type": item["failure_type"],
                                    "count": item["count"],
                                    "percentage": item["percentage"]
                                }
                                for item in top_3
                            ]
                        },
                        recommendations=[
                            f"Priorizar correção de: {top_3[0]['failure_type']} ({top_3[0]['percentage']:.1f}% das falhas)",
                            f"Investigar causas raiz de: {top_3[1]['failure_type']}" if len(top_3) > 1 else "Monitorar tendências",
                            "Implementar ações corretivas nos problemas identificados",
                            "Aplicar Diagrama de Ishikawa para análise de causas",
                        ],
                        timestamp=datetime.now(),
                        data={
                            "tool": "pareto",
                            "pareto_chart": items,
                            "analysis_period": "7 days"
                        }
                    )
                    insights.append(insight)
                    logger.info(f"✅ Generated Pareto insight: {len(vital_few)} vital few identified")

            # 2. FAILURE PATTERN ANALYSIS - Identify recurring patterns
            # Check if we have multiple failures of the same type (indicating systematic issue)
            if pareto_result.get("items"):
                high_frequency_failures = [
                    item for item in pareto_result["items"]
                    if item.get("count", 0) >= 5  # 5 or more occurrences
                ]

                if high_frequency_failures:
                    for failure in high_frequency_failures[:2]:  # Top 2 high-frequency
                        insight = AutonomousInsight(
                            insight_id=f"quality_pattern_{failure['failure_type']}_{datetime.now().timestamp()}",
                            title=f"⚠️ Padrão Recorrente: {failure['failure_type']}",
                            description=(
                                f"Falha '{failure['failure_type']}' ocorreu {failure['count']} vezes "
                                f"nos últimos 7 dias ({failure['percentage']:.1f}% do total). "
                                f"Isso indica um problema sistemático que requer análise de causa raiz."
                            ),
                            category="alert",
                            severity="high" if failure['count'] >= 10 else "medium",
                            tags=["pattern", "recurring", "quality"],
                            metrics={
                                "failure_type": failure['failure_type'],
                                "occurrence_count": failure['count'],
                                "percentage": failure['percentage'],
                                "cumulative_percentage": failure.get('cumulative_percentage', 0)
                            },
                            recommendations=[
                                "Aplicar 5 Porquês para encontrar causa raiz",
                                "Criar Diagrama de Ishikawa (espinha de peixe)",
                                "Verificar se existe padrão temporal (horário, turno, dia)",
                                "Implementar ação corretiva permanente",
                                "Adicionar Check Sheet para rastrear ocorrências"
                            ],
                            timestamp=datetime.now(),
                            data={
                                "tool": "pattern_analysis",
                                "failure_details": failure
                            }
                        )
                        insights.append(insight)

            # 3. PROCESS STABILITY CHECK - Using statistical analysis
            # Check variance in critical process tags
            process_tags = [tag for tag in tags if hasattr(tag, 'category') and
                          tag.category.value in ["process", "control"]][:5]

            for tag in process_tags:
                try:
                    # Get statistics for the tag
                    result = await toolkit.execute_tool(
                        "calculate_statistics",
                        {
                            "tag_id": str(tag.id),
                            "duration": "24h"
                        }
                    )

                    if result.success and result.data:
                        stats = result.data
                        mean = stats.get("mean", 0)
                        stddev = stats.get("stddev", 0)

                        # Calculate coefficient of variation (CV)
                        cv = (stddev / mean * 100) if mean != 0 else 0

                        # High variability indicates unstable process
                        if cv > 15:  # CV > 15% indicates high variability
                            insight = AutonomousInsight(
                                insight_id=f"quality_stability_{tag.id}_{datetime.now().timestamp()}",
                                title=f"📊 Variabilidade Alta: {tag.name}",
                                description=(
                                    f"Tag '{tag.name}' apresenta coeficiente de variação de {cv:.1f}% "
                                    f"(> 15%), indicando processo instável. Média: {mean:.2f}, "
                                    f"Desvio Padrão: {stddev:.2f}."
                                ),
                                category="alert",
                                severity="medium" if cv < 25 else "high",
                                tags=[str(tag.id), "stability", "spc", "quality"],
                                metrics={
                                    "coefficient_of_variation": cv,
                                    "mean": mean,
                                    "stddev": stddev,
                                    "tag_name": tag.name
                                },
                                recommendations=[
                                    "Implementar Carta de Controle (SPC) para monitoramento contínuo",
                                    "Investigar causas de variação especial",
                                    "Verificar se equipamento está operando dentro de especificação",
                                    "Considerar ajuste de parâmetros de controle",
                                    "Aplicar Regras de Western Electric para detectar padrões"
                                ],
                                timestamp=datetime.now(),
                                data={
                                    "tool": "statistical_process_control",
                                    "statistics": stats,
                                    "cv_threshold": 15
                                }
                            )
                            insights.append(insight)
                            logger.info(f"✅ Generated stability insight for {tag.name}: CV={cv:.1f}%")

                except Exception as e:
                    logger.error(f"Error analyzing stability for tag {tag.id}: {e}")

            logger.info(f"✅ Quality insights generation complete: {len(insights)} insights generated")

        except Exception as e:
            logger.error(f"Error in generate_quality_insights: {e}")

        return insights

    def add_insight(self, insight: AutonomousInsight):
        """Add insight to the feed"""
        self.insights.insert(0, insight)  # Add to beginning

        # Keep only max_insights
        if len(self.insights) > self.max_insights:
            self.insights = self.insights[:self.max_insights]

        logger.info(f"📝 New insight: [{insight.severity}] {insight.title}")
    
    def get_insights(
        self,
        category: Optional[str] = None,
        severity: Optional[str] = None,
        limit: int = 20
    ) -> List[Dict[str, Any]]:
        """Get insights with optional filters"""
        filtered = self.insights
        
        if category:
            filtered = [i for i in filtered if i.category == category]
        
        if severity:
            filtered = [i for i in filtered if i.severity == severity]
        
        return [i.to_dict() for i in filtered[:limit]]
    
    def get_dashboard_summary(self) -> Dict[str, Any]:
        """Get summary for dashboard"""
        total = len(self.insights)
        
        by_category = {}
        by_severity = {}
        
        for insight in self.insights:
            by_category[insight.category] = by_category.get(insight.category, 0) + 1
            by_severity[insight.severity] = by_severity.get(insight.severity, 0) + 1
        
        return {
            "total_insights": total,
            "by_category": by_category,
            "by_severity": by_severity,
            "latest_insight": self.insights[0].to_dict() if self.insights else None,
            "monitoring_active": self.is_running,
            "monitoring_interval": self.monitoring_interval
        }


# Global agent instance (will be initialized on startup)
_autonomous_agent: Optional[AutonomousAgent] = None


async def init_autonomous_agent():
    """Initialize autonomous agent"""
    global _autonomous_agent
    _autonomous_agent = AutonomousAgent()
    # Start monitoring in background
    asyncio.create_task(_autonomous_agent.start())
    logger.info("✅ Autonomous Agent initialized and started")


def get_autonomous_agent() -> Optional[AutonomousAgent]:
    """Get autonomous agent instance"""
    return _autonomous_agent
