"""Pydantic schemas for request/response validation"""

from .user import (
    UserBase,
    UserCreate,
    UserUpdate,
    UserResponse,
    Token,
    TokenPayload,
)
from .organization import (
    OrganizationBase,
    OrganizationCreate,
    OrganizationUpdate,
    OrganizationResponse,
)
from .site import (
    SiteBase,
    SiteCreate,
    SiteUpdate,
    SiteResponse,
)
from .device import (
    DeviceBase,
    DeviceCreate,
    DeviceUpdate,
    DeviceResponse,
)
from .tag import (
    TagBase,
    TagCreate,
    TagUpdate,
    TagResponse,
)
from .tag_label import (
    TagLabelBase,
    TagLabelCreate,
    TagLabelUpdate,
    TagLabelResponse,
)
from .alarm import (
    AlarmDefinitionBase,
    AlarmDefinitionCreate,
    AlarmDefinitionUpdate,
    AlarmDefinitionResponse,
    AlarmEventResponse,
    AlarmAcknowledgeRequest,
)
from .analytics import (
    QueryFilter,
    QueryAggregation,
    AnalyticsQuery,
    AnalyticsQueryRequest,
    AnalyticsQueryResponse,
    QueryResult,
    AggregationResult,
    SavedQuery,
    SavedQueryCreate,
    SavedQueryUpdate,
    SavedQueryResponse,
)
from .asset import (
    AssetBase,
    AssetCreate,
    AssetUpdate,
    AssetResponse,
    AssetTreeNode,
    AssetAttributeBase,
    AssetAttributeCreate,
    AssetAttributeUpdate,
    AssetAttributeResponse,
    AssetTemplateBase,
    AssetTemplateCreate,
    AssetTemplateUpdate,
    AssetTemplateResponse,
    AssetInstantiateRequest,
    AttributeDefinition,
)
from .dashboard import (
    GridPosition,
    WidgetBase,
    WidgetCreate,
    WidgetUpdate,
    WidgetResponse,
    DashboardBase,
    DashboardCreate,
    DashboardUpdate,
    DashboardResponse,
    DashboardListResponse,
    DashboardShareBase,
    DashboardShareCreate,
    DashboardShareUpdate,
    DashboardShareResponse,
    DashboardTemplateBase,
    DashboardTemplateCreate,
    DashboardTemplateUpdate,
    DashboardTemplateResponse,
    DashboardCloneRequest,
    DashboardFromTemplateRequest,
    WidgetBulkUpdateRequest,
    DashboardListFilters,
    DashboardStats,
)

__all__ = [
    # User
    "UserBase",
    "UserCreate",
    "UserUpdate",
    "UserResponse",
    "Token",
    "TokenPayload",
    # Organization
    "OrganizationBase",
    "OrganizationCreate",
    "OrganizationUpdate",
    "OrganizationResponse",
    # Site
    "SiteBase",
    "SiteCreate",
    "SiteUpdate",
    "SiteResponse",
    # Device
    "DeviceBase",
    "DeviceCreate",
    "DeviceUpdate",
    "DeviceResponse",
    # Tag
    "TagBase",
    "TagCreate",
    "TagUpdate",
    "TagResponse",
    # Tag Label
    "TagLabelBase",
    "TagLabelCreate",
    "TagLabelUpdate",
    "TagLabelResponse",
    # Alarm
    "AlarmDefinitionBase",
    "AlarmDefinitionCreate",
    "AlarmDefinitionUpdate",
    "AlarmDefinitionResponse",
    "AlarmEventResponse",
    "AlarmAcknowledgeRequest",
    # Analytics
    "QueryFilter",
    "QueryAggregation",
    "AnalyticsQuery",
    "AnalyticsQueryRequest",
    "AnalyticsQueryResponse",
    "QueryResult",
    "AggregationResult",
    "SavedQuery",
    "SavedQueryCreate",
    "SavedQueryUpdate",
    "SavedQueryResponse",
    # Asset
    "AssetBase",
    "AssetCreate",
    "AssetUpdate",
    "AssetResponse",
    "AssetTreeNode",
    "AssetAttributeBase",
    "AssetAttributeCreate",
    "AssetAttributeUpdate",
    "AssetAttributeResponse",
    "AssetTemplateBase",
    "AssetTemplateCreate",
    "AssetTemplateUpdate",
    "AssetTemplateResponse",
    "AssetInstantiateRequest",
    "AttributeDefinition",
    # Dashboard
    "GridPosition",
    "WidgetBase",
    "WidgetCreate",
    "WidgetUpdate",
    "WidgetResponse",
    "DashboardBase",
    "DashboardCreate",
    "DashboardUpdate",
    "DashboardResponse",
    "DashboardListResponse",
    "DashboardShareBase",
    "DashboardShareCreate",
    "DashboardShareUpdate",
    "DashboardShareResponse",
    "DashboardTemplateBase",
    "DashboardTemplateCreate",
    "DashboardTemplateUpdate",
    "DashboardTemplateResponse",
    "DashboardCloneRequest",
    "DashboardFromTemplateRequest",
    "WidgetBulkUpdateRequest",
    "DashboardListFilters",
    "DashboardStats",
]
