"""
Pydantic schemas for chat/conversation API.
"""
from datetime import datetime
from typing import Optional, List, Dict, Any
from pydantic import BaseModel, Field, UUID4
from app.models.chat import MessageRole


# Message schemas
class MessageBase(BaseModel):
    """Base message schema"""
    content: str = Field(..., min_length=1, max_length=10000)
    role: MessageRole


class MessageCreate(MessageBase):
    """Schema for creating a new message"""
    message_metadata: Optional[Dict[str, Any]] = None


class MessageResponse(MessageBase):
    """Schema for message response"""
    id: UUID4
    conversation_id: UUID4
    message_metadata: Optional[Dict[str, Any]] = None
    created_at: datetime

    class Config:
        from_attributes = True


# Conversation schemas
class ConversationBase(BaseModel):
    """Base conversation schema"""
    title: str = Field(..., min_length=1, max_length=255)
    context: Optional[Dict[str, Any]] = None


class ConversationCreate(ConversationBase):
    """Schema for creating a new conversation"""
    pass


class ConversationUpdate(BaseModel):
    """Schema for updating a conversation"""
    title: Optional[str] = Field(None, min_length=1, max_length=255)
    context: Optional[Dict[str, Any]] = None


class ConversationResponse(ConversationBase):
    """Schema for conversation response"""
    id: UUID4
    user_id: UUID4
    organization_id: UUID4
    created_at: datetime
    updated_at: datetime
    messages: List[MessageResponse] = []

    class Config:
        from_attributes = True


class ConversationListResponse(BaseModel):
    """Schema for conversation list response"""
    id: UUID4
    title: str
    created_at: datetime
    updated_at: datetime
    message_count: int = 0

    class Config:
        from_attributes = True


# Chat request/response schemas
class ChatRequest(BaseModel):
    """Schema for chat request"""
    message: str = Field(..., min_length=1, max_length=10000)
    conversation_id: Optional[UUID4] = None
    include_context: bool = Field(default=True, description="Include device/alarm context in AI response")
    context_filters: Optional[Dict[str, Any]] = Field(
        default=None,
        description="Filters for context (e.g., {'site_id': 'uuid', 'device_type': 'plc'})"
    )


class ChatResponse(BaseModel):
    """Schema for chat response"""
    conversation_id: UUID4
    message: MessageResponse
    suggestions: Optional[List[str]] = Field(default=None, description="Suggested follow-up questions")


# Insight schemas
class InsightRequest(BaseModel):
    """Schema for requesting insights"""
    query: str = Field(..., description="Natural language query for insights")
    scope: Optional[str] = Field(default="organization", description="Scope: organization, site, or device")
    entity_id: Optional[UUID4] = Field(default=None, description="ID of site or device if scope is specific")
    time_range: Optional[str] = Field(default="24h", description="Time range for data analysis (e.g., 1h, 24h, 7d)")


class InsightResponse(BaseModel):
    """Schema for insight response"""
    insights: List[str] = Field(..., description="List of insights generated by AI")
    data_summary: Optional[Dict[str, Any]] = Field(default=None, description="Summary of analyzed data")
    recommendations: Optional[List[str]] = Field(default=None, description="Actionable recommendations")
    visualizations: Optional[List[Dict[str, Any]]] = Field(default=None, description="Suggested visualizations")
