"""
Demo Data Endpoints

Endpoints especializados para as views de demonstração:
- Real-time data feed
- Historical data analysis
- Alarms and events aggregation
"""
from fastapi import APIRouter, Depends, HTTPException, Query
from sqlalchemy.ext.asyncio import AsyncSession
from sqlalchemy import select
from typing import List, Optional
from datetime import datetime, timedelta
import random

from app.db.session import get_db
from app.models.tag import Tag
from app.services.influxdb import influxdb_service
from app.models.user import User
from app.core.deps import get_current_user

router = APIRouter()


@router.get("/ai-agent/insights")
async def get_agent_insights(
    limit: int = Query(50, ge=1, le=200),
    current_user: User = Depends(get_current_user)
):
    """
    Get insights from Autonomous Agent

    Returns insights generated by the autonomous monitoring agent.
    Used by Alarms & Events View.
    """
    try:
        from app.services.autonomous_agent import autonomous_agent

        # Get insights from autonomous agent
        insights_list = autonomous_agent.get_insights(limit=limit)

        # Format for frontend
        formatted_insights = []
        for insight in insights_list:
            formatted_insights.append({
                'id': insight.insight_id,
                'insight_id': insight.insight_id,
                'title': insight.title,
                'description': insight.description,
                'category': insight.category,
                'severity': insight.severity,
                'tags': insight.tags,
                'metrics': insight.metrics,
                'recommendations': insight.recommendations,
                'timestamp': insight.timestamp.isoformat() if hasattr(insight.timestamp, 'isoformat') else str(insight.timestamp),
                'data': insight.data
            })

        return formatted_insights

    except Exception as e:
        # If agent not running, return empty list
        return []


@router.get("/tags/realtime")
async def get_realtime_tags(
    limit: int = Query(default=50, ge=1, le=200),
    category: Optional[str] = Query(default=None),
    current_user: User = Depends(get_current_user),
    db: AsyncSession = Depends(get_db)
):
    """
    Get real-time data for multiple tags

    Returns current values for all active tags with simulated quality and trends.
    Used by Real-Time Data View.

    Parameters:
    - limit: Maximum number of tags to return (1-200)
    - category: Filter by category (optional)
    """
    try:
        # Get tags from database
        stmt = select(Tag).where(Tag.is_active == True)

        if category and category != 'all':
            stmt = stmt.where(Tag.category == category)

        stmt = stmt.limit(limit)
        result = await db.execute(stmt)
        tags = result.scalars().all()

        # Get real-time values from InfluxDB
        realtime_data = []

        for tag in tags:
            try:
                # Try to get real value from InfluxDB
                latest_value = influxdb_service.get_latest_value(tag.name)

                if latest_value:
                    value = latest_value.get('value', 0)
                    timestamp = latest_value.get('timestamp', datetime.now().isoformat())
                    quality = 'good'
                else:
                    # Generate simulated data if no real data
                    value = random.uniform(
                        tag.min_value if tag.min_value else 0,
                        tag.max_value if tag.max_value else 100
                    )
                    timestamp = datetime.now().isoformat()
                    quality = 'good'

                realtime_data.append({
                    'name': tag.name,
                    'tag_name': tag.name,
                    'value': round(value, 2),
                    'unit': tag.unit or '',
                    'timestamp': timestamp,
                    'quality': quality,
                    'category': tag.category.value if hasattr(tag.category, 'value') else str(tag.category),
                    'description': tag.description or ''
                })

            except Exception as e:
                # If error, use simulated data
                value = random.uniform(0, 100)
                realtime_data.append({
                    'name': tag.name,
                    'tag_name': tag.name,
                    'value': round(value, 2),
                    'unit': tag.unit or '',
                    'timestamp': datetime.now().isoformat(),
                    'quality': 'good',
                    'category': tag.category.value if hasattr(tag.category, 'value') else str(tag.category),
                    'description': tag.description or ''
                })

        return realtime_data

    except Exception as e:
        raise HTTPException(status_code=500, detail=f"Error fetching realtime data: {str(e)}")


@router.get("/tags/history")
async def get_tag_history(
    tag_name: str = Query(default="energy_consumption"),
    time_range: str = Query(default='last_24h', pattern='^(last_24h|last_7_days|last_30_days|last_90_days)$'),
    aggregation: str = Query(default='raw', pattern='^(raw|1m|5m|1h|1d)$'),
    current_user: User = Depends(get_current_user)
):
    """
    Get historical data for a specific tag

    Used by Historical Data Analysis View.

    Parameters:
    - tag_name: Name of the tag
    - time_range: Time range (last_24h, last_7_days, last_30_days, last_90_days)
    - aggregation: Data aggregation (raw, 1m, 5m, 1h, 1d)
    """
    try:
        # Parse time range
        time_ranges = {
            'last_24h': timedelta(hours=24),
            'last_7_days': timedelta(days=7),
            'last_30_days': timedelta(days=30),
            'last_90_days': timedelta(days=90)
        }

        duration = time_ranges.get(time_range, timedelta(days=7))
        start_time = datetime.now() - duration

        # Get data from InfluxDB
        try:
            data = influxdb_service.query_tag_history(
                tag_name=tag_name,
                start_time=start_time,
                aggregation=aggregation
            )
        except:
            # If InfluxDB fails, generate simulated data
            data = _generate_simulated_history(tag_name, duration, aggregation)

        return {
            'tag_name': tag_name,
            'time_range': time_range,
            'aggregation': aggregation,
            'data': data
        }

    except Exception as e:
        raise HTTPException(status_code=500, detail=f"Error fetching historical data: {str(e)}")


@router.get("/tags/list")
async def list_tag_names(
    current_user: User = Depends(get_current_user),
    db: AsyncSession = Depends(get_db)
):
    """
    Get list of all tag names

    Used by Historical Data Analysis View for tag selection.
    """
    try:
        stmt = select(Tag).where(Tag.is_active == True).order_by(Tag.name)
        result = await db.execute(stmt)
        tags = result.scalars().all()

        return [
            {
                'name': tag.name,
                'description': tag.description or '',
                'unit': tag.unit or '',
                'category': tag.category.value if hasattr(tag.category, 'value') else str(tag.category)
            }
            for tag in tags
        ]

    except Exception as e:
        raise HTTPException(status_code=500, detail=f"Error listing tags: {str(e)}")


def _generate_simulated_history(tag_name: str, duration: timedelta, aggregation: str) -> List[dict]:
    """Generate simulated historical data"""

    # Determine number of points based on aggregation
    points_map = {
        'raw': int(duration.total_seconds() / 10),  # Every 10 seconds
        '1m': int(duration.total_seconds() / 60),
        '5m': int(duration.total_seconds() / 300),
        '1h': int(duration.total_seconds() / 3600),
        '1d': int(duration.days)
    }

    num_points = min(points_map.get(aggregation, 100), 1000)  # Max 1000 points

    data = []
    now = datetime.now()

    # Base value with some variation
    base_value = random.uniform(50, 150)

    for i in range(num_points):
        timestamp = now - (duration * (1 - i / num_points))

        # Add some noise and trend
        noise = random.uniform(-10, 10)
        trend = (i / num_points) * random.uniform(-20, 20)
        value = base_value + noise + trend

        data.append({
            'timestamp': timestamp.isoformat(),
            'value': round(value, 2),
            'tag_name': tag_name,
            'quality': 'good' if random.random() > 0.05 else 'uncertain'
        })

    return data
