"""
ML Drift Monitoring API Endpoints

Provides endpoints for:
- Data drift detection
- Model performance monitoring
- Drift reports and alerts
- Retraining triggers
"""

from fastapi import APIRouter, Depends, HTTPException, Query
from sqlalchemy.ext.asyncio import AsyncSession
from typing import Optional, List
from datetime import datetime, timedelta
import logging

from app.db.session import get_db
from app.services.ml_drift_detector import get_drift_detector
from app.models.user import User
from app.core.deps import get_current_user
from pydantic import BaseModel

router = APIRouter()
logger = logging.getLogger(__name__)


class DriftCheckRequest(BaseModel):
    """Request for drift detection"""
    model_name: str
    reference_period_days: int = 30  # Training data period
    current_period_days: int = 7     # Recent data period
    target_column: Optional[str] = None
    numerical_features: Optional[List[str]] = None
    categorical_features: Optional[List[str]] = None


class DriftCheckResponse(BaseModel):
    """Response from drift detection"""
    data_drift: dict
    performance_drift: Optional[dict] = None
    should_retrain: bool
    retraining_decision: dict
    timestamp: str


@router.post("/check", response_model=DriftCheckResponse)
async def check_model_drift(
    request: DriftCheckRequest,
    db: AsyncSession = Depends(get_db),
    current_user: User = Depends(get_current_user)
):
    """
    Check for data and performance drift in ML model

    Compares reference (training) data with current production data
    to detect distribution changes and performance degradation.

    **Process**:
    1. Load reference data (training period)
    2. Load current data (recent production)
    3. Run Evidently drift detection
    4. Check model performance metrics
    5. Determine if retraining is needed

    **Returns**:
    - Data drift metrics and drifted features
    - Performance drift metrics
    - Retraining recommendation (urgency: high/medium/low)

    **Example Response**:
    ```json
    {
        "data_drift": {
            "drift_detected": true,
            "drift_score": 0.65,
            "drifted_features": ["temperature", "pressure"],
            "recommendation": "RETRAINING REQUIRED"
        },
        "performance_drift": {
            "performance_drift_detected": true,
            "current_metrics": {"accuracy": 0.82},
            "baseline_metrics": {"accuracy": 0.95},
            "metric_drops": {"accuracy": 0.13}
        },
        "should_retrain": true,
        "retraining_decision": {
            "urgency": "high",
            "reason": "Data drift: 65% AND Performance degradation"
        }
    }
    ```
    """
    try:
        drift_detector = get_drift_detector()

        # TODO: Load reference and current data from database
        # For now, returning placeholder response
        logger.warning(f"Drift check requested for model '{request.model_name}' - data loading not yet implemented")

        # Placeholder response
        return DriftCheckResponse(
            data_drift={
                "drift_detected": False,
                "drift_score": 0.0,
                "drifted_features": [],
                "drift_report_path": None,
                "recommendation": "Data loading not yet implemented"
            },
            performance_drift=None,
            should_retrain=False,
            retraining_decision={
                "should_retrain": False,
                "reason": "No data loaded for analysis",
                "urgency": "low",
                "triggers": []
            },
            timestamp=datetime.utcnow().isoformat()
        )

    except Exception as e:
        logger.error(f"Error checking drift: {e}", exc_info=True)
        raise HTTPException(
            status_code=500,
            detail=f"Failed to check drift: {str(e)}"
        )


@router.get("/reports")
async def list_drift_reports(
    limit: int = Query(20, ge=1, le=100),
    current_user: User = Depends(get_current_user)
):
    """
    List recent drift detection reports

    Returns list of drift reports generated by Evidently AI,
    with metadata about drift detection results.

    **Use Cases**:
    - Review historical drift trends
    - Identify patterns in data distribution changes
    - Audit retraining decisions
    """
    try:
        drift_detector = get_drift_detector()
        reports_dir = drift_detector.reports_dir

        if not reports_dir.exists():
            return {
                "reports": [],
                "total": 0,
                "reports_dir": str(reports_dir)
            }

        # List HTML reports
        reports = sorted(
            reports_dir.glob("drift_report_*.html"),
            key=lambda p: p.stat().st_mtime,
            reverse=True
        )[:limit]

        report_list = []
        for report_path in reports:
            stat = report_path.stat()
            report_list.append({
                "filename": report_path.name,
                "path": str(report_path),
                "created_at": datetime.fromtimestamp(stat.st_mtime).isoformat(),
                "size_bytes": stat.st_size
            })

        return {
            "reports": report_list,
            "total": len(report_list),
            "reports_dir": str(reports_dir)
        }

    except Exception as e:
        logger.error(f"Error listing drift reports: {e}", exc_info=True)
        raise HTTPException(
            status_code=500,
            detail=f"Failed to list reports: {str(e)}"
        )


@router.get("/status")
async def get_drift_monitoring_status(
    current_user: User = Depends(get_current_user)
):
    """
    Get current status of drift monitoring system

    Returns configuration and health status of drift detection service.

    **Returns**:
    - Drift thresholds
    - Performance thresholds
    - Number of reports generated
    - Evidently AI availability
    """
    try:
        drift_detector = get_drift_detector()

        # Check Evidently availability
        try:
            import evidently
            evidently_version = evidently.__version__
            evidently_available = True
        except ImportError:
            evidently_version = None
            evidently_available = False

        # Count reports
        reports_dir = drift_detector.reports_dir
        num_reports = len(list(reports_dir.glob("drift_report_*.html"))) if reports_dir.exists() else 0

        return {
            "status": "healthy" if evidently_available else "degraded",
            "evidently_available": evidently_available,
            "evidently_version": evidently_version,
            "configuration": {
                "drift_threshold": drift_detector.drift_threshold,
                "performance_threshold": drift_detector.performance_threshold,
                "reports_dir": str(drift_detector.reports_dir)
            },
            "statistics": {
                "total_reports": num_reports
            },
            "message": "Drift monitoring operational" if evidently_available else "Evidently AI not installed"
        }

    except Exception as e:
        logger.error(f"Error getting drift status: {e}", exc_info=True)
        raise HTTPException(
            status_code=500,
            detail=f"Failed to get status: {str(e)}"
        )


@router.post("/trigger-retraining/{model_name}")
async def trigger_model_retraining(
    model_name: str,
    reason: Optional[str] = None,
    current_user: User = Depends(get_current_user)
):
    """
    Manually trigger model retraining

    Starts background retraining task for specified model.

    **Use Cases**:
    - Manual retraining after detecting drift
    - Scheduled retraining by automation
    - Emergency retraining after incidents

    **Args**:
    - model_name: Name of model to retrain
    - reason: Optional reason for retraining (logged for audit)

    **Returns**:
    - Task ID for tracking retraining progress
    - Estimated completion time
    """
    try:
        from app.tasks.ml_tasks import retrain_models_task

        # Trigger Celery task
        task = retrain_models_task.delay(
            organization_id=str(current_user.organization_id),
            models_to_train=model_name
        )

        logger.info(f"Retraining triggered for model '{model_name}' by user {current_user.email}")
        if reason:
            logger.info(f"Reason: {reason}")

        return {
            "status": "retraining_started",
            "task_id": task.id,
            "model_name": model_name,
            "triggered_by": current_user.email,
            "reason": reason or "Manual trigger",
            "estimated_time": "5-10 minutes",
            "message": f"Retraining task {task.id} started in background"
        }

    except ImportError:
        raise HTTPException(
            status_code=503,
            detail="Celery not available - cannot trigger background retraining"
        )
    except Exception as e:
        logger.error(f"Error triggering retraining: {e}", exc_info=True)
        raise HTTPException(
            status_code=500,
            detail=f"Failed to trigger retraining: {str(e)}"
        )
